server:
  port: 8080
  context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/data.db
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true
  thymeleaf:
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true