server:
  port: 9090
  context-path: /
  tomcat:
    uri-encoding: utf-8
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/data.db
    username: root
    password: 123456
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update